### ISSUE TITLE
MassAssignmentException in Model.php

### ISSUE THREAD

**Issue by appdezign** [Laravel-Backpack/Generators#12]
First of all, I really love Backpack, especially the CRUD package. Great work.

I was under the impression that, when using the generators, the new CRUD would work out of the box. But when I test it, using the example from the Docs, I get an exception:

```
MassAssignmentException in Model.php line 444:
name
```

When I look at the Model that was created, I see that the fillable is still commented out.
Is this intended behaviour? Should I edit the Model, the Controller and the Request manually?
Or am I doing something wrong?

Any help would be greatly appreciated

**Comment by OwenMelbz** [comment]
@appdezign it does, however what you're describing is laravel specific. 

You couldn't populate the fillable automatically array as we have no idea what you'd want to be put in it.

Even if you had uncommented fillable array, that error would still happen because your using the CRUD to update a model, but you've not setup the permission/fillable on your model.

There's nothing we can really do about that, it's just how laravel works, if you try to do a mass assignment illegally it will error.

The reason it's there is just to give new comers the ability to easily add their own fillable.

I'll close this up now just to keep the area tidy, but if you have any more questions I'm sure somebody can answer them :)
