### ISSUE TITLE
Issue about abstract class 

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/Generators#175]
tomorrow is another day 👍

**Comment by tabacitu** [comment]
It truly is! 😀 But future us are never going to remember what this was about. So let's be clear:
- https://github.com/Laravel-Backpack/Generators/pull/171 introduced an abstract class, `BackpackCommand` that had nothing abstract about it;
- Pedro asked for it to be made non-abstract;
- Mauro did;
- I merged;

But what neither Mauro nor I have done... is test. 👀 It broke everything. So Pedro had to push a hotfix in https://github.com/Laravel-Backpack/Generators/pull/174 to save our asses 🙏

Now this issue is here so we remember to un-abstract that class, but also test and see what else needs fixing if we do that.

**Comment by pxpm** [comment]
I was supposed to write that tomorrow, this was assigned to me 🙃 

See you 😴

**Comment by pxpm** [comment]
We will keep it abstract for the foreseeable feature. There is nothing "broken", so aesthetics are not in the list RN.
