### ISSUE TITLE
Make generated code cleaner

### ISSUE THREAD

**Issue by praswicaksono** [Laravel-Backpack/Generators#23]
I think it is better to strip comment inside generated code since it already explained in docs. Also generated code are not `PSR2` compliant. I can submit pull request if this suggestion approved

**Comment by tabacitu** [comment]
Hi @praswicaksono , thanks for asking! 

You're referring to the comments from the CrudController, right? I personally find the comments useful, since the documentation is not yet as clear as I had wanted and the IDE autocomplete is still fuzzy. It helps me do 90% of what I need without getting out of the controller file. This makes it a lot faster to write admin panels. After I finish it, I delete all the commented code.

I expect the autocomplete/codeintel to work a lot better after [this update, though](https://github.com/Laravel-Backpack/CRUD/issues/394), so I'd postpone eliminating the comments until then.

But if there's a majority thinking the way you do, sure, we delete them. Let's wait for more people to pitch in, see what they think.

Cheers!

**Comment by OwenMelbz** [comment]
I was thinking about this the other day, and had an idea I wanted to implement, but wasn't going to bother unless it was gonna get merged lol.

My idea was something along the lines of

php artisan backpack:generate --exclude-comments

php artisan backpack:generate --include-comments

This would write to a config like file, setting the defaults for your generator commands.

Then additionally if you ran a command like

php artisan backpack:generate CrudController --exclude-comments

It would do it on per command basis.

As I've got familiar with the system, I now get annoyed by these extra comments haha.

If you'd be willing to try something out like that I can give it a whirl!?

**Comment by praswicaksono** [comment]
@tabacitu Im sure intelligent IDE will detect autocompletion if you hinted `$crud` property with right object. 

https://github.com/Laravel-Backpack/CRUD/blob/master/src/app/Http/Controllers/CrudController.php#L25

add phpdocs to property

```php
/**
* @var CrudPanel
*/
public $crud;
```

Intelligent IDE should able detect auto completion.

**Comment by uniconstructor** [comment]
As I mentioned in [this issue](https://github.com/Laravel-Backpack/Generators/issues/27) you can solve this problem by using [AST-based code generation](https://github.com/nikic/PHP-Parser/blob/master/doc/4_Code_generation.markdown) instead of file templates.

**Comment by tabacitu** [comment]
Hi guys, 

The plan right now is to make generators smarter first:
- models to have relationships, $fillable attributes, etc;
- form requests to have some sensible defaults (ex: required for not null columns);

Then we'll start generating Backpack code in the controller instead of using ```setFromDb()```.
Then I think it will be ok to remove the comments, since most people won't need them anymore.

Let me know what you think.
Cheers!
