### ISSUE TITLE
Laracasts Generators issue making a migration

### ISSUE THREAD

**Issue by jbowm2** [Laravel-Backpack/Generators#33]
After install on Laravel 5.5 continue to receive this error when trying to create a migration:

php artisan make:migration:schema create_tags_table --schema="name:string:unique" --model=0

Method Laracasts\Generators\Commands\MigrationMakeCommand::handle() does n  
  ot exist

**Comment by FascistDonut** [comment]
I am having the same issue. 

Also:

[Symfony\Component\Debug\Exception\FatalErrorException]
  Trait 'Illuminate\Console\AppNamespaceDetectorTrait' not found

**Comment by chilly2go** [comment]
Some problem. No solution found yet

**Comment by chilly2go** [comment]
looking at the error message it looks like a simple method is missing so I added:

    /**
     * fire method seems to handle everything but does not get called
     */
    public function handle ()
    {
        $this->fire();
    }

which did the trick for me. It might be popssible that other commands still throw exceptions but make:migration:schema now works for me.

**Comment by brytorres** [comment]
@chilly2go that worked! Thanks!

**Comment by tabacitu** [comment]
Hi guys,

There was an issue with Laracasts\Generators at the time - it didn't support the latest Laravel version. We've since been granted write access to it, and will be keeping an eye on it for it to be working. Right now, as always, you can expect for it to be working after a ```composer update```.

Thanks for the issue.
Cheers!
