### ISSUE TITLE
Request: backpack:crud-model to generate migration

### ISSUE THREAD

**Issue by OwenMelbz** [Laravel-Backpack/Generators#5]
Love the work you've done so far, is much appreciated :)

Im starting to have a little dig around, and wondered what the possibility of adding the migration creation to the model generation?

For example a normal artisan command would be `php artisan make:model Cake --migration` and you'd get a migration with it.

Would this functionality be possible to add (or does it already exist?)

Many thanks for your hard work.

Owen

**Comment by tabacitu** [comment]
Hi @OwenMelbz ,

Yes, it's on the roadmap. For that, I plan on using the excellent [Laracasts/Generators](https://github.com/laracasts/Laravel-5-Generators-Extended), which you can use right now to speed up development. 

I found that [this is the fastest way](https://laravel-backpack.readme.io/docs/crud-example#doing-it-all-very-fast) to develop CRUDs right now. In a future version, I hope to transform this entire process:
```sh
php artisan make:migration:schema create_tags_table --schema="name:string:unique" --model=0
php artisan migrate
php artisan backpack:crud tag
# then manually add this to your routes.php file (under the admin prefix and auth middleware):
# CRUD::resource('tag', 'TagCrudController');
```
into one command. So this will bring commands like:
```sh
# generate a migration
php artisan backpack:crud-migration tag

# generate a complete CRUD in one line (migration, run migration, controller with fields already
# placed, auto-enable reorder if necessary columns are in the db, model with fillable attributes,
# request with required on NOT NULL columns, route)
php artisan backpack:crud tag tags --schema="name:string:unique"

# OPTIONAL FLAG: also generate pivot tables for n-n relationships
 --pivot="articles,posts,comments"

# OPTIONAL FLAG: also generate seeds
 --seed
```

I also plan on creating a command-line wizard to make remembering the syntax above unnecessary:
```php
php artisan backpack:crud-wizard
# You are about to generate a new Backpack/CRUD panel.
# 1) What's the name of the entity you're creating? (singular, will be used for the model name)
tag
# 2) What's the name of the entity (plural)? (will be used for the table name)
tags
# 3) Generate migration? (y/n)
y
   # 3.1) Migration schema? (ex: "name:string:unique, description:text"
   name:string:unique, description:text:nullable
   # 3.2) Pivot tables to any tables?
   articles,categories
# 4) Generate seed? (y/n)
y
# 5) Migration generated. Please confirm migration is final (y/n). (your editor should open)
y
# 6) Done:
# - ran migration: database/migrations/2016_05_25_121918_create_tags_table
# - generated controller: app/Http/Controllers/Admin/TagCrudController.php
# - generated model: app/Models/Tag.php
# - generated request: app/Http/Requests/TagRequest.php
# - added route under admin namespace and prefix: CRUD::resource('tag', 'TagCrudController');

```
It's a lot of work, but when it's finished, it should speed up both development and new users' understanding of Backpack. 

What do you think?

**Comment by OwenMelbz** [comment]
Morning!

Overall this does seem like a pretty nice feature to have, I feel the automatic route insertion will be the most complicated component, unless you consider abstracting the routes into a configuration file (array style) which can be parsed and manipulated, more easily than all the different ways a route could be added?

Additionally maybe an option to generate a custom request file? Not a high priority feature, but maybe something worth considering.

For step 5 I'm a little confused about the migration generated, please confirm its final? I'm not entirely sure I understand what that step is for?

Final thought would be that it would also be nice to include the permission generation in this wizard :)

But overall this does seem like a very good feature to have, and will make it easier/faster for people to start scaffolding apps out quicker!

**Comment by OwenMelbz** [comment]
PR is now in place for this

**Comment by b8ne** [comment]
Hey guys, Ive been thinking about this feature a bit over the last few days, turns out youre all already on top of it.
When building cruds ive found the 2 most repetitive tasks are filling model data and creating controllers. I can imagine controller generation would be near impossible to automate, so it may be worthwhile building that into the setup wizard.
ie setup migration -> setup crud -> automate model data/relationships -> iterate each db field and get `type` input for both columns and fields.
This would save a lot of time.

**Comment by tabacitu** [comment]
@b8ne - I agree with you that THAT is the next thing we should automate. My thought was for:
- the generated migration to already have everything in fillable
- the generated migration to already have the relationships defined
- the generated controller to already have all fields added (instead of using ```setFromDb()```)

**Comment by b8ne** [comment]
Sorry guys @tabacitu @OwenMelbz  I know this issue is closed, don't think its worth creating another issue though. I just found [this](https://www.reddit.com/r/laravel/comments/67gie4/turning_the_artisan_make_command_into_an) which looks promising. May be worth giving it a look and utilising it's backbone. I'm flat out mid semester at the moment, but if it's not done by the end of May i'd be keen to give it a crack.
