### ISSUE TITLE
Cannot create a migration when following the getting started tutorial without errors

### ISSUE THREAD

**Issue by justageek** [Laravel-Backpack/Generators#94]
# Bug report

### What I did:
Ran the command php artisan make:migration create_tags_table --schema="name:string:unique,slug:string:unique"
### What I expected to happen:
the migration to be created for a Tag entity
### What happened:
Got this error
There are no commands defined in the "make:migration" namespace.  
                                                                    
  Did you mean this?                                                
      make   
### What I've already tried to fix it:
just cleared cache, autoload dump
### Backpack, Laravel, PHP, DB version:
Backpack: latest 4.x
Laravel: 7.10.3
DB version: 5.7.29-0ubuntu0.18.04.1

**Comment by tabacitu** [comment]
Hi @justageek ,

That's weird. I suspect you either:
- haven't done `composer require --dev laracasts/generators` as instructed in the [Backpack installation page](https://backpackforlaravel.com/docs/4.1/installation#install-core-packages) - that's the third-party package that enables the `php artisan make:migration:schema` command (take note of the last part, `schema`);
- or if the command that doesn't work for you is `php artisan make:migration` (no `schema`), it's possible you haven't [properly installed Laravel](https://laravel.com/docs/7.x/installation); that command is part of Laravel itself; can you open Laravel's welcome page just fine?

Hope it helps.
Cheers!

PS. In the future we'll probably stop recommending [laracasts/generators](https://github.com/laracasts/Laravel-5-Generators-Extended) in favour of [laravel-shift/blueprint](https://github.com/laravel-shift/blueprint), because it also writes the relationships. Or _maybe_ recommend both. What I'm saying is - you can use anything you want to generate your Eloquent models. What's important from Backpack's point of view is that afterwards you create a CRUD for that model.
